import NextAuthSesssionProvider from '@/providers/SesssionProvider';
import QueryProvider from '@/providers/QueryProvider';
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthSesssionProvider>
        <QueryProvider>
          {children}
        </QueryProvider>
      </NextAuthSesssionProvider>
      </body>
    </html>
  )
}
